name: Docker

on:
  push:
    tags: ["**"]
    branches: ["main"]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Comma-separate list of additional tags for built image.'
        required: false
        default: 'latest'

env:
  SHA: "${{ github.sha }}"
  SHORT_SHA: "${SHA:0:7}"
  REF_NAME: "${{ github.ref_name }}"

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build, tag and push docker image to ghcr
        uses: GlueOps/github-actions-build-push-containers@v0.4.2
        with:
          tags: ${SHA},${SHORT_SHA},${REF_NAME},${{ inputs.tags }}
