name: Docker

on:
  workflow_run:
    workflows: [XXX]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Build, tag and push docker image to ghcr
        uses: GlueOps/github-actions-build-push-containers@v0.4.2
        with:
          tags: "${{ github.sha }},${{ github.ref_name }},latest"
