name: Release

run-name: release version ${{ inputs.version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'part of the project version to update'
        options:
        - major
        - minor
        - patch
        required: true

env:
  PIP_NO_OPTION: on
  PIP_NO_CLEAN: on
  PIP_PREFER_BINARY: on

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache requirements
        uses: actions/cache@v4
        env:
          cache-name: cache-requirements
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: make setup

      - name: Release new version
        id: release
        run: |
          git config --global user.name 'RKIMetadataExchange'
          git config --global user.email 'mex@rki.de'
          pdm release ${{ inputs.version }}
          echo "version=${{ inputs.version }}" >> "$GITHUB_OUTPUT"

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release
    steps:
      - name: Build, tag and push docker image to ghcr
        uses: GlueOps/github-actions-build-push-containers@v0.4.2
        with:
          tags: "${{ github.sha }},${{ github.ref_name }},${{ needs.release.outputs.version }},latest"
